# Generated by Django 3.0.6 on 2021-01-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0003_auto_20210107_0957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='products',
        ),
    ]
