# Generated by Django 3.0.6 on 2021-01-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0005_auto_20210117_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tagas',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
