# Generated by Django 3.0.6 on 2021-01-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0006_products_tagas'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='reviews',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
