# Generated by Django 3.0.6 on 2021-01-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0007_products_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='reviews',
        ),
    ]
