# Generated by Django 3.0.6 on 2021-01-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0008_remove_products_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='reviews',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
