# Generated by Django 3.0.6 on 2021-02-03 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0009_products_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='tagas',
            new_name='tags',
        ),
    ]
