# Generated by Django 3.0.6 on 2021-02-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0010_auto_20210203_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='tags',
            new_name='category',
        ),
    ]
