# Generated by Django 3.0.6 on 2021-02-09 10:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('istore', '0011_auto_20210203_1047'),
        ('customer', '0003_auto_20210119_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=10)),
                ('user', models.CharField(max_length=256)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 2, 9, 10, 42, 7, 224858))),
                ('address', models.CharField(max_length=256)),
                ('contact_no', models.IntegerField(max_length=10)),
                ('price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='istore.products')),
            ],
        ),
    ]
